### ISSUE TITLE
"OpenAi response was empty"

### ISSUE THREAD

**Issue by FireGh0st** [manekinekko/minecraft-openai#6]
Project Clone 
Minecraft: 1.17
Node: 16.15.0
The bot connects, takes the context, but when it has to call the OpenAi API, no response from the API
the log:
![cmd_h9D5fydgD8](https://user-images.githubusercontent.com/65304881/165954309-216dd89f-b9a9-4b77-a918-1010805fa861.png)
![cmd_qX8YPnJh12](https://user-images.githubusercontent.com/65304881/165954305-baa63880-936b-4c23-b60a-dd10808ec626.png)

**Comment by RomainWeber** [comment]
I have a same issue. I tried on Postman and i got this error
![image](https://user-images.githubusercontent.com/46939527/168049741-da717326-9395-4ae1-92df-df5fef206a49.png)

**Comment by manekinekko** [comment]
I am sorry, but the Codex engine we are using might not be available to everyone, which is why you are getting the empty response. You will need to wait until OpenAI gives you access.

**Comment by FireGh0st** [comment]
Ok thanks, i will try later

**Comment by manekinekko** [comment]
Thank you @FireGh0st and sorry for the inconvenience!
